#!/bin/bash
curl -v -XPOST -H "Content-type: application/json" -d '{ 
  "name": "Maria Jose Quintanilla",
  "email": "mjosequinta@gmail.com",
  "password": "Pantoesico%",
  "phones": []
}' 'http://localhost:8080/user/sign-up'
