#!/bin/bash
curl -v -XPOST -H "Content-type: application/json" -d '{ 
  "name": "Patricio Oviedo",
  "email": "patricio.hernandez@gmail.com",
  "password": "a2asfGfdfdf45553@##",
  "phones": [{
    "number": 1,
    "cityCode": 56,
    "contryCode": "CL"
  }]
}' 'http://localhost:8080/user/sign-up'
